name: Master
on:
  push:
    branches:
      - master

jobs:
  master:
    if: "! startsWith(github.event.head_commit.message, '[CI Skip]')"
    strategy:
      matrix:
        step: ['build:release']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_PAT_BOT }}
    - uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
    - name: ${{ matrix.step }}
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        GH_PAT: ${{ secrets.GH_PAT_BOT }}
        GH_RELEASE_GITHUB_API_TOKEN: ${{ secrets.GH_PAT_BOT }}
        GH_RELEASE_FILES: master-build.zip,master-src.zip
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        yarn install --immutable | grep -v 'YN0013'
        yarn ${{ matrix.step }}
